<?php
/**
 * 2020-05-17
 * 1) "Implement a custom design for the `post/list.phtml` template":
 * https://github.com/tradefurniturecompany/blog/issues/1
 * 2) I have restored the template from the 1.3.0.24 version of the `FishPig_WordPress` module:
 * https://github.com/bentideswell/magento2-wordpress-integration/blob/1.3.0.24/view/frontend/templates/post/list/renderer/default.phtml
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class='post-list-item'>
		<h2>
			<a href='<?= $post->getUrl() ?>' title='<?= $this->escapeHtml($post->getName()) ?>'>
				<?= $this->escapeHtml($post->getName()) ?>
			</a>
		</h2>
		<div class='post-date post-meta-item'><?= $post->getPostDate() ?></div>
		<div class='post-entry'>
			<?php if ($image = $post->getImage()): ?>
				<div class='post-image'>
					<a href='<?= $post->getUrl() ?>' title='<?= $this->escapeHtml($post->getName()) ?>'><img src='<?= $image->getAvailableImage() ?>' alt='<?= $this->escapeHtml($post->getName()) ?>'/></a>
				</div>
			<?php endif; ?>
			<div class='post-excerpt'><?= $post->getExcerpt(60) ?></div>
		</div>
	</div>
<?php endif; ?>