<?php
/**
 * 2020-05-17
 * 1) "Implement a custom design for the `post/list.phtml` template":
 * https://github.com/tradefurniturecompany/blog/issues/1
 * 2) I have restored the template from the 1.3.0.24 version of the `FishPig_WordPress` module:
 * https://github.com/bentideswell/magento2-wordpress-integration/blob/1.3.0.24/view/frontend/templates/post/list/renderer/default.phtml
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-list-item">
		<h2>
			<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>">
				<?php echo $this->escapeHtml($post->getName()) ?>
			</a>
		</h2>
		<div class="post-entry">
			<?php if ($image = $post->getImage()): ?>
				<div class="post-image">
					<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>"><img src="<?php echo $image->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getName()) ?>"/></a>
				</div>
			<?php endif; ?>
			<div class="post-excerpt"><?php echo $post->getExcerpt(60) ?></div>
		</div>
		<div class="post-meta">
			<?php if ($categoryString = $post->getTermCollectionAsString('category')): ?>
				<div class="post-categories post-meta-item">
					<strong><?php echo __('Categories') ?>:</strong> <?php echo $categoryString ?>
				</div>
			<?php endif; ?>
			<?php if ($tagString = $post->getTermCollectionAsString('post_tag')): ?>
				<div class="post-tags post-meta-item">
					<strong><?php echo __('Tags') ?>:</strong> <?php echo $tagString ?>
				</div>
			<?php endif; ?>
			<div class="post-date post-meta-item">
				<strong><?php echo __('Posted On') ?>:</strong> <?php echo $post->getPostDate() ?>
			</div>
			<div class="post-user post-meta-item">
				<strong><?php echo __('Posted By') ?>:</strong> <a href="<?php echo $post->getUser()->getUrl() ?>"><?php echo $post->getUser() ->getDisplayName() ?></a>
			</div>
		</div>
	</div>
<?php endif; ?>