<?php if ($post = $this->getPost()) { ?>
	<div class='post-view'>
		<div class='post-date post-meta-item'><?= $post->getPostDate() ?></div>
		<div class='post-entry'>
			<?php if ($image = $post->getImage()) {
				/**
				 * 2020-03-25
				 * 1) "Force blog images to have the same dimensions
				 * as it was before the 1.3.0.24 → 2.0.11.14 `FishPig_WordPress` module upgrade":
				 * https://github.com/tradefurniturecompany/core/issues/27
				 * 2) I have ported the solution from 1.3.0.24:
				 * https://github.com/bentideswell/magento2-wordpress-integration/blob/1.3.0.24/view/frontend/templates/post/view.phtml#L14
				 */
				$imageUrl = $image->getAvailableImage(); ?>
				<div class='post-image'>
					<a href='<?= $post->getUrl() ?>' title='<?= $this->escapeHtml($post->getPostTitle()) ?>'><img src='<?= $imageUrl ?>' alt='<?= $this->escapeHtml($post->getPostTitle()) ?>'/></a>
				</div>
			<?php } ?>
			<?php if (($content = trim($post->getContent())) !== '') { ?>
				<div class='post-content'><?= $content ?></div>
			<?php } ?>
		</div>
	</div>
<?php } ?>